CREATE TABLE `single_of_week_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(120) NOT NULL,
	`age` int NOT NULL,
	`city` varchar(120) NOT NULL,
	`phone` varchar(32) NOT NULL,
	`selfDescription` text NOT NULL,
	`desiredPartner` text NOT NULL,
	`relationshipStatus` enum('single','divorced','widowed','separated','other') NOT NULL,
	`hasChildren` boolean NOT NULL,
	`instagramUsername` varchar(30) NOT NULL,
	`photoKey` varchar(512) NOT NULL,
	`photoUrl` varchar(1024) NOT NULL,
	`photoFilename` varchar(255) NOT NULL,
	`photoMimeType` varchar(32) NOT NULL,
	`photoSizeBytes` int NOT NULL,
	`databaseMembershipConsent` boolean NOT NULL,
	`instagramFollowConsent` boolean NOT NULL,
	`publicationConsent` boolean NOT NULL,
	`consentedAt` timestamp NOT NULL DEFAULT (now()),
	`reviewStatus` enum('new','reviewing','approved','rejected') NOT NULL DEFAULT 'new',
	`reviewedAt` timestamp,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `single_of_week_applications_id` PRIMARY KEY(`id`)
);
