/**
 * Design: “Champagne at Midnight” — official Plus terms with an editorial midnight
 * membership frame, champagne membership signals and a continuous ivory reading surface.
 */
import { Link } from "wouter";
import { ArrowLeft, CheckCircle2, Sparkles } from "lucide-react";

const SECTIONS = [
  ["השירות ומי רשאי להצטרף", "Plus הוא מסלול אופציונלי לחברים ולחברות פעילים במאגר הרווקים של הילית כספי, בעלי פרופיל מלא ומאושר. השירות אינו מחליף את החברות הרגילה במאגר ואינו שירות ליווי אישי או זמינות 24/7."],
  ["מה כולל Plus", "בכל מחזור חיוב פעיל השירות כולל לכל הפחות שתי הצעות התאמה חדשות שנבדקו ונשלחו ללקוח/ה בפועל, קדימות בתשומת הלב לפרופיל, ובוסט אחד נוסף. אין בהצעות התחייבות לאישור הדדי, לפגישה, לזוגיות או לתוצאה כלשהי."],
  ["מהי הצעת התאמה", "הצעה נספרת רק כאשר היא חדשה, נבדקה ונשלחה בפועל. שליחה חוזרת של אותו אדם אינה נספרת פעמיים. התאמה יכולה להישלח גם בציון נמוך מ־80% כאשר לאחר בחינה מקצועית אני מאמינה שיש בה פוטנציאל, וכל עוד היא אינה סותרת תנאי סף מהותיים של שני הצדדים. אם חסרה הצעה בתום המחזור, היא נותרת התחייבות שירות ומועברת למחזור הבא."],
  ["בוסט — מהו ומה משמעות ההשתתפות", "בוסט הוא הצעה נוספת מעבר לשתי ההתאמות שבמסלול Plus. הוא מבוסס על נתוני הפרופיל וההעדפות, ועשוי להישלח לפני בדיקה ידנית של הילית; לכן הוא מסומן בבירור כהצעת בוסט ואינו נספר כאחת משתי ההתאמות. ההצטרפות ל-Plus כוללת אישור מפורש לקבלת בוסטים והבנה של משמעותם. אי-מימוש בוסט במחזור פעיל אינו נצבר למחזור הבא."],
  ["המחיר והחידוש האוטומטי", "מחיר המסלול הוא 99 ש״ח לחודש, כולל מע״מ, בנוסף לדמי ההצטרפות או החברות הרגילה במאגר. המנוי מתחדש אוטומטית מדי חודש עד לביטול. לפני התשלום נדרש אישור נפרד וברור לחידוש האוטומטי. החיוב יתבצע רק באמצעות עמוד הוראת קבע מאובטח ומאושר של Grow."],
  ["ביטול", "ניתן למסור בקשת ביטול בכל עת דרך האזור האישי או דרך שירות הלקוחות. הבקשה תירשם ותעצור חידושים עתידיים בהתאם למדיניות הביטול שתוצג בעמוד התשלום ובאזור האישי. המסלול יישאר פעיל עד תום התקופה ששולמה. ביטול Plus אינו מבטל את החברות הרגילה במאגר."],
  ["פינת הרווקים", "חשיפה בפינת הרווקים היא אפשרות וולונטרית בלבד, ואינה תנאי למסלול Plus, להתאמות או לבוסט. סימון רצון לשמוע על החשיפה הוא בקשת עניין בלבד. פרסום ייעשה רק לאחר אישור מפורש ונפרד של הלקוח/ה לתמונה ולטקסט הסופי; פרטי קשר לא יפורסמו."],
  ["שירות ותקשורת", "השירות כולל מענה בעדיפות לשאלות, בקשות ועדכון העדפות בשעות הפעילות. השירות אינו תחליף לייעוץ, לליווי אישי או למענה חירום."],
  ["כשל תשלום", "במקרה של כשל בחיוב תישלח הודעה ותינתן אפשרות סבירה לעדכון אמצעי התשלום. הטבות Plus עשויות להיות מושהות עד להסדרת התשלום. החברות הרגילה במאגר אינה נפגעת מכשל בחיוב Plus."],
  ["יצירת קשר ושינויים", "לשאלות, בקשות ביטול או עדכון העדפות אפשר לפנות לשירות הלקוחות העסקי: 055-244-2334. שינויים מהותיים בתנאי Plus יפורסמו מראש באתר או באזור האישי."],
];

function Lockup() { return <Link href="/database-plus" className="flex items-center gap-3"><span className="relative grid h-11 w-11 place-items-center rounded-full border border-[#d8b67e]/45 bg-[#d8b67e]/10"><span className="font-serif text-2xl font-bold text-[#e8cb91]">+</span><Sparkles className="absolute -right-1 -top-1 h-3.5 w-3.5 text-[#e8cb91]" /></span><span><span className="block text-[10px] font-bold tracking-[.17em] text-[#e7c98e]">HILIT CASPI</span><span className="mt-0.5 block font-serif text-xl font-bold text-white">Plus</span></span></Link>; }

export default function TermsPlus() {
  return <main className="min-h-screen overflow-x-hidden bg-[#0c1327] font-rubik text-[#17213d]" dir="rtl"><header className="border-b border-white/10 bg-[#10182f]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 md:px-10"><Lockup /><Link href="/database-plus" className="flex items-center gap-2 text-sm text-white/70 transition-colors hover:text-[#e8cb91]"><ArrowLeft className="h-4 w-4" />חזרה לעמוד Plus</Link></div></header><section className="relative isolate overflow-hidden border-b border-[#d8b67e]/25 bg-[#10182f] px-5 pb-20 pt-16 text-white md:px-10 md:pb-24 md:pt-20"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_86%_18%,rgba(216,182,126,.18),transparent_0_22%),radial-gradient(circle_at_12%_85%,rgba(85,107,165,.16),transparent_0_26%)]" /><div className="mx-auto max-w-6xl"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 border border-[#d8b67e]/40 bg-white/5 px-3 py-2 text-xs font-bold tracking-[.11em] text-[#e8cb91]"><Sparkles className="h-4 w-4" />OFFICIAL MEMBERSHIP DOCUMENT</span><p className="mt-8 text-xs font-bold tracking-[.18em] text-[#d8b67e]">DATABASE PLUS / TERMS</p><h1 className="mt-4 font-serif text-5xl font-bold leading-[.94] md:text-7xl">תקנון Plus <span className="text-[#e8cb91]">ומדיניות ביטול</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-white/72">מסמך החברות שמבהיר בדיוק מה כולל המסלול, איך פועל הבוסט, ומה מאשרים לפני התשלום.</p></div></div></section><section className="bg-[#ede2cf] px-5 py-12 md:px-10 md:py-20"><div className="mx-auto max-w-6xl"><div className="border border-[#c6a66e]/40 bg-[#fffaf1] shadow-[0_28px_70px_rgba(0,0,0,.15)]"><div className="border-b border-[#17213d]/10 px-6 py-5 md:flex md:items-center md:justify-between md:px-10"><p className="text-xs font-bold tracking-[.16em] text-[#9c7436]">PLUS MEMBERSHIP / ISSUE 01</p><p className="mt-2 text-xs text-[#646a74] md:mt-0">טיוטת תוכן לבדיקה משפטית לפני פרסום</p></div><div className="divide-y divide-[#17213d]/12 px-6 md:px-10">{SECTIONS.map(([title, body], index) => <section key={title} className="grid gap-4 py-8 md:grid-cols-[78px_1fr] md:gap-8 md:py-10"><span className="font-serif text-4xl font-bold leading-none text-[#b48c4b]">{String(index + 1).padStart(2, "0")}</span><div><h2 className="text-xl font-bold text-[#17213d] md:text-2xl">{title}</h2><p className="mt-3 max-w-3xl text-sm leading-8 text-[#4d5361] md:text-base">{body}</p></div></section>)}</div><div className="border-t border-[#d8b67e]/45 bg-[#fff5de] px-6 py-6 md:px-10"><div className="flex items-start gap-3 text-sm leading-7 text-[#604c27]"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-[#aa7b35]" />בעמוד ההצטרפות נדרש אישור מפורש לתקנון זה, לחידוש האוטומטי ולהשתתפות בבוסטים לפני המשך לתשלום.</div></div></div></div></section></main>;
}
