/**
 * Design: “Champagne at Midnight” — official branded addendum for Plus and Boost.
 */
import { Link } from "wouter";
import { ArrowLeft, CheckCircle2, Info, Sparkles } from "lucide-react";

const ADDITIONS = [
  ["Plus הוא מסלול אופציונלי", "החברות הרגילה במאגר נשארת נפרדת. הצטרפות ל-Plus אינה משנה את תנאי החברות הבסיסיים ואינה מבטיחה תוצאה, פגישה או זוגיות. היא מוסיפה התחייבות שירות מוגדרת: שתי התאמות חדשות לכל הפחות במחזור חיוב פעיל ובוסט נוסף."],
  ["התאמות מקצועיות גם מעבר לציון", "ציון ההתאמה הוא כלי מסייע בלבד. התאמה שציון ההתאמה שלה נמוך מ־80% עשויה להישלח כאשר קיימת הערכה מקצועית שיש בה פוטנציאל ובהתקיים תנאי הסף החשובים של שני הצדדים."],
  ["בוסט הוא הצעה נוספת ומסומנת", "כל לקוח או לקוחה ב-Plus נותנים הסכמה מפורשת לקבלת בוסטים כחלק מההצטרפות. בוסט מבוסס על נתוני הפרופיל ועל העדפות, עשוי להגיע לפני בדיקה ידנית, והוא אינו נספר כאחת משתי ההתאמות במסלול Plus."],
  ["חשיפה בפינת הרווקים", "חשיפה אינה אוטומטית. לקוחות Plus יכולים לבחור לבקש מידע על פינת הרווקים, אך פרסום מותנה תמיד באישור מפורש ונפרד לתוכן הסופי. פרטי קשר לא יפורסמו."],
];

function Lockup() {
  return <Link href="/database-plus" className="flex items-center gap-3"><span className="relative grid h-11 w-11 place-items-center rounded-full border border-[#d8b67e]/45 bg-[#d8b67e]/10"><span className="font-serif text-2xl font-bold text-[#e8cb91]">+</span><Sparkles className="absolute -right-1 -top-1 h-3.5 w-3.5 text-[#e8cb91]" /></span><span><span className="block text-[10px] font-bold tracking-[.17em] text-[#e7c98e]">HILIT CASPI</span><span className="mt-0.5 block font-serif text-xl font-bold text-white">Plus</span></span></Link>;
}

export default function TermsDatabase() {
  return <main className="min-h-screen overflow-x-hidden bg-[#0c1327] font-rubik text-[#17213d]" dir="rtl"><header className="border-b border-white/10 bg-[#10182f]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 md:px-10"><Lockup /><Link href="/database-plus" className="flex items-center gap-2 text-sm text-white/70 transition-colors hover:text-[#e8cb91]"><ArrowLeft className="h-4 w-4" />חזרה לעמוד Plus</Link></div></header><section className="relative isolate overflow-hidden border-b border-[#d8b67e]/25 bg-[#10182f] px-5 pb-20 pt-16 text-white md:px-10 md:pb-24 md:pt-20"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_22%,rgba(216,182,126,.14),transparent_0_20%),radial-gradient(circle_at_92%_85%,rgba(84,107,165,.16),transparent_0_25%)]" /><div className="mx-auto max-w-6xl"><div className="max-w-3xl"><p className="text-xs font-bold tracking-[.18em] text-[#d8b67e]">DATABASE / OFFICIAL ADDENDUM</p><h1 className="mt-5 font-serif text-5xl font-bold leading-[.94] md:text-7xl">עדכון תקנון המאגר:<span className="mt-2 block text-[#e8cb91]">Plus ובוסטים</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-white/72">מסמך שמציג במפורש את מקום Plus והבוסט בתוך החברות הקיימת במאגר.</p></div></div></section><section className="bg-[#ede2cf] px-5 py-12 md:px-10 md:py-20"><div className="mx-auto max-w-6xl"><div className="border border-[#c6a66e]/40 bg-[#fffaf1] shadow-[0_28px_70px_rgba(0,0,0,.15)]"><div className="border-b border-[#17213d]/10 px-6 py-5 md:flex md:items-center md:justify-between md:px-10"><p className="text-xs font-bold tracking-[.16em] text-[#9c7436]">DATABASE / PLUS ADDENDUM</p><span className="mt-2 inline-flex items-center gap-2 text-xs font-medium text-[#626875] md:mt-0"><CheckCircle2 className="h-4 w-4 text-[#a77c37]" />תנאים משלימים לחברי Plus בלבד</span></div><div className="divide-y divide-[#17213d]/12 px-6 md:px-10">{ADDITIONS.map(([title, body], index) => <section key={title} className="grid gap-4 py-9 md:grid-cols-[78px_1fr] md:gap-8 md:py-11"><span className="font-serif text-4xl font-bold leading-none text-[#b48c4b]">{String(index + 1).padStart(2, "0")}</span><div><h2 className="text-xl font-bold md:text-2xl">{title}</h2><p className="mt-3 max-w-3xl text-sm leading-8 text-[#4d5361] md:text-base">{body}</p></div></section>)}</div><div className="border-t border-[#d8b67e]/45 bg-[#fff5de] px-6 py-7 md:px-10"><div className="flex items-start gap-3 text-sm leading-7 text-[#5d4a29]"><Info className="mt-1 h-5 w-5 shrink-0 text-[#9c7436]" />בעת ההצטרפות ל-Plus נדרש אישור נפרד של התקנון, חיוב חודשי מתחדש והשתתפות בבוסטים. למסמך המלא: <Link href="/terms/plus" className="font-bold underline underline-offset-4">תקנון Plus ומדיניות ביטול</Link>.</div></div></div></div></section></main>;
}
