import { useMemo, useState } from "react";
import { BarChart3, CircleHelp, ClipboardPenLine, Loader2, Plus, TrendingUp } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";

function idempotencyKey() { return typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; }
const CATEGORY_LABELS: Record<string, string> = { database: "מאגר", dashboard: "דשבורד", content: "תוכן", tracking: "מדידה וקמפיינים" };
function metricValue(value: any, preferred: "tasks" | "minutes" = "tasks") { if (typeof value === "number") return value; if (preferred === "minutes" && typeof value?.durationMs === "number") return Math.round((value.durationMs / 60000) * 10) / 10; return Number(value?.[preferred] ?? value?.events ?? value?.count ?? value?.total ?? value?.value ?? 0); }
function label(value: any, fallback: string) { return value?.labelHe || value?.label || value?.name || fallback; }
function objectRows(value: any, key: string): any[] { if (Array.isArray(value)) return value; if (value && typeof value === "object") return Object.entries(value).map(([name, item]) => typeof item === "object" ? { [key]: name, ...item } : { [key]: name, tasks: item }); return []; }

export default function UsageShiftSection() {
  const api = trpc as any;
  const now = Date.now();
  const [range] = useState(() => ({ startDate: now - 29 * 24 * 60 * 60 * 1000, endDate: now }));
  const overview = api.usage.overview.useQuery(range, { refetchOnWindowFocus: false });
  const catalog = api.usage.catalog.useQuery(undefined, { refetchOnWindowFocus: false });
  const actions = useMemo(() => Array.isArray(catalog.data?.actions) ? catalog.data.actions : [], [catalog.data]);
  const categories = useMemo(() => Array.from(new Map(actions.map((item: any) => [item.category, CATEGORY_LABELS[item.category] || item.category])).entries()).map(([value, text]) => ({ value, label: text })), [actions]);
  const [category, setCategory] = useState("");
  const allowedActions = useMemo(() => actions.filter((item: any) => !category || item.category === category), [actions, category]);
  const [actionKey, setActionKey] = useState("");
  const [channel, setChannel] = useState<"manus" | "manual">("manual");
  const record = api.usage.recordManualTask.useMutation({ onSuccess: () => { setActionKey(""); overview.refetch(); } });
  const data = overview.data || {};
  const totals = data.totals || {};
  const baseline = data.baseline;
  const byCategory = objectRows(data.byCategory, "category");
  const byAction = objectRows(data.byAction, "actionKey");
  const dailyTrend = objectRows(data.dailyTrend, "date");
  const taskLogObserved = data.taskLogObserved;
  const maxTrend = Math.max(1, ...dailyTrend.map(item => metricValue(item)));
  const save = () => { if (!category || !actionKey || record.isPending) return; record.mutate({ category, actionKey, channel, idempotencyKey: idempotencyKey(), occurredAt: Date.now() }); };

  return <div dir="rtl" className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
    <div className="space-y-5">
      <Card className="border-[#191265]/10 shadow-sm"><CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-xl text-[#191265]"><TrendingUp className="size-5" />מה עבר לביצוע עצמי</CardTitle><CardDescription className="mt-1">מעקב תפעולי אחר משימות שבוצעו עצמאית, מתוך תיעוד המערכת והצוות.</CardDescription></div><Badge className="border-0 bg-[#fff3bf] text-[#191265] hover:bg-[#fff3bf]">תפעול בלבד</Badge></div></CardHeader><CardContent><div className="rounded-xl border border-[#ffe27c] bg-[#fffdf5] p-3 text-sm leading-6 text-[#191265]"><CircleHelp className="ml-1 inline size-4 align-text-bottom" />אין נתוני חיוב או קרדיטים מאומתים של Manus. התצוגה משקפת שימוש ומשימות שתועדו בלבד — לא עלות, חיוב, קרדיטים או הערכה כספית.</div></CardContent></Card>
      {overview.isLoading ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[1, 2, 3, 4].map(item => <div key={item} className="h-24 animate-pulse rounded-2xl bg-[#191265]/10" />)}</div> : overview.error ? <Card className="border-[#191265]/10"><CardContent className="p-5 text-sm text-slate-500">לא ניתן לטעון את נתוני השימוש כרגע.</CardContent></Card> : <>
        <Card className="border-[#191265]/10 shadow-sm"><CardHeader className="pb-2"><CardTitle className="text-lg text-[#191265]">הנתונים הנוכחיים</CardTitle><CardDescription>מדידה מתועדת לטווח 30 הימים האחרונים.</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><MetricTile label="פעולות מתועדות" value={metricValue(totals, "tasks")} /><MetricTile label="טוקני AI בתוך האתר" value={Number(totals.promptTokens || 0) + Number(totals.completionTokens || 0)} /><MetricTile label="סוגי פעולה חדשים" value={Array.isArray(data.newActionKeys) ? data.newActionKeys.length : 0} /><MetricTile label="ערוצים פעילים" value={Array.isArray(data.byChannel) ? data.byChannel.length : 0} /></div></CardContent></Card>
        {baseline && <BaselineCard baseline={baseline} />}
        {taskLogObserved && <TaskLogObservedCard observed={taskLogObserved} />}
        <div className="grid gap-5 lg:grid-cols-2"><MetricsCard title="לפי קטגוריה" icon={<BarChart3 className="size-4" />} rows={byCategory} rowKey="category" /><MetricsCard title="לפי פעולה" icon={<ClipboardPenLine className="size-4" />} rows={byAction} rowKey="actionKey" /></div>
        <Card className="border-[#191265]/10 shadow-sm"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-lg text-[#191265]"><TrendingUp className="size-4" />מגמה יומית</CardTitle></CardHeader><CardContent>{dailyTrend.length === 0 ? <p className="text-sm text-slate-500">מגמה תופיע לאחר שיצטבר תיעוד יומי.</p> : <div className="flex h-44 items-end gap-2 overflow-x-auto pb-1">{dailyTrend.map((item: any) => { const value = metricValue(item); return <div key={item.date} className="flex min-w-10 flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-bold text-[#191265]">{value}</span><div className="w-full max-w-12 rounded-t-lg bg-[#191265]" style={{ height: `${Math.max(8, (value / maxTrend) * 108)}px` }} /><span className="max-w-14 truncate text-[10px] text-slate-500" title={item.date}>{item.date}</span></div>; })}</div>}</CardContent></Card>
      </>}
    </div>
    <Card className="h-fit border-[#191265]/10 shadow-sm"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-lg text-[#191265]"><Plus className="size-5" />תיעוד משימה</CardTitle><CardDescription>הזנה קצרה של משימה שנעשתה ב-Manus או ידנית. נשמרת רק זהות משימה מאושרת.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>קטגוריה</Label><Select value={category} onValueChange={value => { setCategory(value); setActionKey(""); }}><SelectTrigger className="border-[#191265]/20"><SelectValue placeholder="בחרי קטגוריה" /></SelectTrigger><SelectContent>{categories.map(item => <SelectItem key={String(item.value)} value={String(item.value)}>{String(item.label)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>פעולה</Label><Select value={actionKey} onValueChange={setActionKey} disabled={!category}><SelectTrigger className="border-[#191265]/20"><SelectValue placeholder="בחרי פעולה" /></SelectTrigger><SelectContent>{allowedActions.map((item: any) => <SelectItem key={item.key || item.actionKey} value={item.key || item.actionKey}>{item.labelHe || item.label || item.key || item.actionKey}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>מקור ביצוע</Label><Select value={channel} onValueChange={(value: "manus" | "manual") => setChannel(value)}><SelectTrigger className="border-[#191265]/20"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="manual">ידני</SelectItem><SelectItem value="manus">Manus</SelectItem></SelectContent></Select></div><Button type="button" onClick={save} disabled={!category || !actionKey || record.isPending} className="w-full bg-[#191265] text-white hover:bg-[#191265]/90">{record.isPending && <Loader2 className="ml-1 size-4 animate-spin" />}שמירת תיעוד</Button>{record.error && <p className="text-xs text-red-700">{record.error.message || "לא ניתן לשמור כרגע."}</p>}{record.isSuccess && <p className="text-xs font-bold text-emerald-700">התיעוד נשמר.</p>}</CardContent></Card>
  </div>;
}

function MetricTile({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-[#191265]/[0.04] p-3"><span className="block text-2xl font-bold text-[#191265]">{Number.isInteger(value) ? value : value.toFixed(1)}</span><span className="mt-1 block text-xs text-slate-500">{label}</span></div>; }
function BaselineCard({ baseline }: { baseline: any }) { const streams = Array.isArray(baseline.byWorkstream) ? baseline.byWorkstream : []; return <Card className="border-[#ffe27c] bg-[#fffdf5] shadow-sm"><CardHeader className="pb-2"><CardTitle className="text-lg text-[#191265]">Baseline מתועד</CardTitle><CardDescription>{baseline.period?.startDate} עד {baseline.period?.endDate} · נתון ייחוס נפרד מהמדידה הנוכחית</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:max-w-md"><MetricTile label="משימות" value={metricValue(baseline.totals, "tasks")} /><MetricTile label="דקות מתועדות" value={metricValue(baseline.totals, "minutes")} /></div>{streams.length > 0 && <div className="mt-4 grid gap-2 sm:grid-cols-2">{streams.map((stream: any) => <div key={stream.key} className="flex items-center justify-between gap-2 rounded-lg border border-[#191265]/10 bg-white px-3 py-2 text-xs"><span className="text-slate-600">{stream.labelHe || stream.key}</span><strong className="text-[#191265]">{metricValue(stream, "tasks")} משימות · {metricValue(stream, "minutes")} דק׳</strong></div>)}</div>}{baseline.noteHe && <p className="mt-4 text-xs leading-5 text-[#191265]/75">{baseline.noteHe}</p>}</CardContent></Card>; }
function TaskLogObservedCard({ observed }: { observed: any }) { const rows = Array.isArray(observed.byAction) ? observed.byAction : []; return <Card className="border-[#191265]/10 shadow-sm"><CardHeader className="pb-2"><CardTitle className="text-lg text-[#191265]">משימות Manus חדשות שנצפו</CardTitle><CardDescription>{observed.available ? `נאספות אוטומטית מיומן המשימות החל מ־${observed.since}` : "יומן המשימות אינו זמין כרגע בסביבת האתר"}</CardDescription></CardHeader><CardContent>{!observed.available ? <p className="text-sm text-slate-500">הפעולות בתוך האתר עדיין נמדדות כרגיל.</p> : <><div className="grid grid-cols-2 gap-3 sm:max-w-md"><MetricTile label="משימות חדשות ביומן" value={Number(observed.counts || 0)} /><MetricTile label="סוגים שלא היו בקטלוג" value={Array.isArray(observed.newActionKeys) ? observed.newActionKeys.length : 0} /></div>{rows.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{rows.slice(0, 8).map((row: any) => <Badge key={row.actionKey} variant="outline" className="border-[#191265]/15 text-[#191265]">{row.actionKey} · {row.count}</Badge>)}</div>}</>}</CardContent></Card>; }
function MetricsCard({ title, icon, rows, rowKey }: { title: string; icon: React.ReactNode; rows: any[]; rowKey: string }) { const max = Math.max(1, ...rows.map(item => metricValue(item))); return <Card className="border-[#191265]/10 shadow-sm"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base text-[#191265]">{icon}{title}</CardTitle></CardHeader><CardContent>{rows.length === 0 ? <p className="text-sm text-slate-500">אין עדיין נתונים להצגה.</p> : <div className="space-y-3">{rows.slice(0, 6).map(item => <div key={item[rowKey]}><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="truncate text-slate-600">{label(item, item[rowKey])}</span><strong className="text-[#191265]">{metricValue(item)}</strong></div><div className="h-2 overflow-hidden rounded-full bg-[#191265]/10"><div className="h-full rounded-full bg-[#191265]" style={{ width: `${(metricValue(item) / max) * 100}%` }} /></div></div>)}</div>}</CardContent></Card>; }

export { UsageShiftSection };
